config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/blog_pages' => 'blog_page#index', as: 'blog_pages'
  post '/blog_pages' => 'blog_page#create', as: 'create_blog_page'
  get '/blog_pages/new' => 'blog_page#new', as: 'new_blog_page'
  get '/blog_pages/:id/edit' => 'blog_page#edit', as: 'edit_blog_page'
  patch '/blog_pages/:id' => 'blog_page#update'
  get '/blog_pages/:id' => 'blog_page#show', as: 'blog_page'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_page.rb
class BlogPage < ApplicationRecord
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_page_controller.rb
class BlogPageController < ApplicationController
    def index
        @blog_pages = BlogPage.all
    end
    def show
        @blog_page = BlogPage.find(params[:id])
    end
     
  def new
    @blog_page = BlogPage.new
  end

  def create
    @blog_page = BlogPage.create(blog_page_params)
    
    if @blog_page.valid?
      redirect_to blog_page_path(@blog_page)#, notice: 'Blog page was successfully created.'
    #else
            
     # render 'new'
    end
  end
  
  def edit
    @blog_page = BlogPage.find(params[:id])
  end
 
  def update
    @blog_page = BlogPage.find(params[:id])

    if @blog_page.update(blog_page_params)
      redirect_to blog_page_path(@blog_page), notice: 'Blog page was successfully updated.'
    else
     render 'edit'
    end
  end

  private
  
  def blog_page_params
    params.require(:blog_page).permit(:title, :content)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_page_helper.rb
module BlogPageHelper
end

app/views/blog_page/edit.html.erb
<h1>Edit Blog Page</h1>

<%= form_with model: @blog_page, url: blog_page_path(@blog_page), method: :patch do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit 'Update Blog Page' %>
  </div>
<% end %>

<%= link_to 'Back to All Blog Pages', blog_pages_path %>

app/views/blog_page/index.html.erb
<h1>All Blog Pages</h1>
<ul>
  <% @blog_pages.each do |blog_page| %>
    <li>
      <%= link_to blog_page.title, blog_page_path(blog_page) %>
    </li>
  <% end %>
</ul>

app/views/blog_page/new.html.erb
<h3>Add a New Blog Page</h3>

<%= form_with model: @blog_page, url: blog_pages_path, method: :post do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Blog Page' %>
  </div>
<% end %>
<%= link_to 'Back to All Blog Pages', blog_pages_path %>

app/views/blog_page/show.html.erb
<h1><%= @blog_page.title %></h1>
<p><%= @blog_page.content %></p>

<%= link_to 'Back to All Blog Pages', blog_pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackSample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>